#!/bin/bash

set -o errexit
set -o nounset

function die() {
  echo -e $*
  exit 1
}

nargs=3
if [[ $# -ne $nargs ]]; then
  die "Exactly $nargs arguments required!\$0 <input_path> <frame_rate> <output_path>"
fi

# Input and output variables
input_path="$1"
frame_rate="$2"
output_path="$3"

ffmpeg \
  -i "$input_path" \
  -pix_fmt yuv420p \
  -vcodec ffv1 \
  -level 3 \
  -g 1 \
  -threads 8 \
  -slicecrc 1 \
  -slices 24 \
  -sws_flags lanczos \
  -vf scale=iw*2:ih*2 \
  -acodec flac \
  -r "$frame_rate" \
  -y "$output_path"
