#!/bin/sh

set -o nounset

die() {
  echo $*
  exit 1
}

getmtime() {
  echo $(stat -c %Y $1)
}

# Check if inotify-tools is installed.
for p in inotifywait pandoc; do
  command -v $p >/dev/null || die "inotify-tools and pandoc"
done

trap "exit" INT

if [ $# -lt 1 ]; then
  die "No input name given"
fi
input="$1"
output="${input%.*}.pdf"

if [ ! -e "$input" ]; then
  die "File $input not found"
fi

pandoc "$input" -o "$output"
evince "$output" &

mtime=$(getmtime $input)
while true; do
  pandoc "$input" -o "$output"
  inotifywait -qq -e close_nowrite "$input"
  newmtime=$(getmtime $input)
  if [ $newmtime -eq $mtime ]; then
    continue
  fi
  mtime=$newmtime
done
