#!/bin/sh

killall -q polybar

while pgrep -u $USER -x polybar >/dev/null; do sleep 1; done

if [ "$(uname -n)" = "helge" ]; then
  export BATTERY=""
else
  export BATTERY="battery"
fi

polybar bla &
