#!/usr/bin/env python

import sys

from mutagen.mp3 import MP3


if __name__ == "__main__":
    for path in sys.argv[1:]:
        try:
            audio = MP3(path)
        except:
            pass
        else:
            print(path)
            print("-" * len(path))
            print(audio.pprint())
            print()
