#!/bin/sh

set -o nounset
set -o errexit

die() {
  echo $*
  exit 1
}

getmtime() {
  echo $(stat -c %Y $1)
}

# Check if inotify-tools is installed.
for p in inotifywait rubber-info; do
  command -v $p >/dev/null || die "inotify-tools and rubber required"
done

trap "exit" INT

if [ $# -lt 1 ]; then
  die "No input name given"
fi
input="${1%.*}"
logfile="${input}.log"

mtime=$(getmtime $logfile)
while true; do
  info=$(rubber-info "$input")
  reset
  date +"%d.%m.%Y %H:%M:%S:"
  echo "===================="
  echo -n "$info"
  echo -e "\n"
  inotifywait -qq -e close_nowrite "$logfile"
  newmtime=$(getmtime $logfile)
  if [ $newmtime -eq $mtime ]; then
    continue
  fi
  mtime=$newmtime
done
